/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppRetentionRouteImport } from './routes/_app.retention'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppFollowUpsRouteImport } from './routes/_app.follow-ups'
import { Route as AppContentRouteImport } from './routes/_app.content'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppContactsNewRouteImport } from './routes/_app.contacts.new'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppRetentionRoute = AppRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsNewRoute = AppContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agents': typeof AppAgentsRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/content': typeof AppContentRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/pipeline': typeof AppPipelineRoute
  '/proposals': typeof AppProposalsRoute
  '/retention': typeof AppRetentionRoute
  '/services': typeof AppServicesRoute
  '/workflows': typeof AppWorkflowsRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/contacts/': typeof AppContactsIndexRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AppAgentsRoute
  '/content': typeof AppContentRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/pipeline': typeof AppPipelineRoute
  '/proposals': typeof AppProposalsRoute
  '/retention': typeof AppRetentionRoute
  '/services': typeof AppServicesRoute
  '/workflows': typeof AppWorkflowsRoute
  '/': typeof AppIndexRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/contacts': typeof AppContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agents': typeof AppAgentsRoute
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/content': typeof AppContentRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/proposals': typeof AppProposalsRoute
  '/_app/retention': typeof AppRetentionRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/contacts/new': typeof AppContactsNewRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/contacts'
    | '/content'
    | '/follow-ups'
    | '/pipeline'
    | '/proposals'
    | '/retention'
    | '/services'
    | '/workflows'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/content'
    | '/follow-ups'
    | '/pipeline'
    | '/proposals'
    | '/retention'
    | '/services'
    | '/workflows'
    | '/'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agents'
    | '/_app/contacts'
    | '/_app/content'
    | '/_app/follow-ups'
    | '/_app/pipeline'
    | '/_app/proposals'
    | '/_app/retention'
    | '/_app/services'
    | '/_app/workflows'
    | '/_app/'
    | '/_app/contacts/$id'
    | '/_app/contacts/new'
    | '/_app/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retention': {
      id: '/_app/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AppRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/new': {
      id: '/_app/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AppContactsNewRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
  }
}

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
  AppContactsNewRoute: typeof AppContactsNewRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
  AppContactsNewRoute: AppContactsNewRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppContentRoute: typeof AppContentRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppRetentionRoute: typeof AppRetentionRoute
  AppServicesRoute: typeof AppServicesRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppContentRoute: AppContentRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppRetentionRoute: AppRetentionRoute,
  AppServicesRoute: AppServicesRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
